version: '3.8'

services:
  strapi:
    build: .
    image: strapi-artifakt
    ports:
      - "8888:80"
    env_file: 
      - .env
    volumes:
      - data:/data
      - uploads:/uploads

volumes:
  data:
  uploads:
#  mysqldata:
