version: '3.8'

services:
  strapi:
    build: .
    command: npm run develop
    ports:
      - "1337:1337"
    env_file: 
      - .env
    volumes:
      - data:/data
      - uploads:/uploads

  mysql:
    image: mysql:5
    platform: linux/amd64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  data:
  uploads:
  mysqldata:
